services:
    default_connection:
        class: TYPO3\CMS\Core\Database\Connection
        factory: [ 'CedricZiel\Simplebase\Framework\Database\ConnectionFactory', 'getConnection' ]
    controller_resolver:
        class: CedricZiel\Simplebase\Framework\Controller\ControllerResolver
        arguments: ['@service_container', '@controller_name_parser']
    controller_name_parser:
        class: CedricZiel\Simplebase\Framework\Controller\ControllerNameParser
        arguments: ['@kernel']
    entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['CedricZiel\Simplebase\Framework\Database\EntityManagerFactory', 'getDefaultEntityManager']

    # Routing Layer
    router_listener:
        class: CedricZiel\Simplebase\Framework\Routing\RouterListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_subscriber }
    router:
        alias: router.default
    routing.loader:
        class: CedricZiel\Simplebase\Framework\Routing\DelegatingLoader
        arguments: ['@controller_name_parser', '@routing.resolver']
    routing.resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver
        public: false
    router.default:
        class: CedricZiel\Simplebase\Framework\Routing\Router
        arguments: ['@service_container', '@?', [], '@router.request_context']
    router.request_context:
        class: Symfony\Component\Routing\RequestContext

